version: 2

models:
  - name: stg_orders
    description: "Cleaned orders from Olist"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null

  - name: stg_customers
    description: "Cleaned customers from Olist"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null

  - name: stg_payments
    description: "Cleaned payments from Olist"
    columns:
      - name: order_id
        tests:
          - not_null

  - name: stg_products
    description: "Cleaned products from Olist"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null